#!/usr/bin/env python3
"""Write bottles.html, the Bottles at Sea reading room, from tools/poems.json.

    python3 tools/make-bottles-page.py

Each poem in poems.json becomes one slide of the poem carousel, newest
first, addressable as bottles.html#<slug>. Add a poem's full text as a
"text" field (blank lines between stanzas) and rerun; until then the slide
shows its excerpts and a placeholder.
"""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POEMS = json.loads((ROOT / "tools" / "poems.json").read_text())
GLASS = ["rose", "lime", "dusk"]
ROMAN = "I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI XVII XVIII XIX XX".split()


def esc(s):
    return html.escape(s).replace("\n", "<br>")


def inline(s):
    """*italic*, **bold**, ***bold italic*** inside an escaped line."""
    s = html.escape(s)
    s = re.sub(r"\*\*\*(.+?)\*\*\*", r"<strong><em>\1</em></strong>", s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"\*(.+?)\*", r"<em>\1</em>", s)
    return s


def lines(text):
    """One block per line, keeping the poem's own indentation (1 space = .25em);
    blank lines become stanza breaks, a lone "—" a section break."""
    out, stanza = [], []

    def flush():
        if stanza:
            out.append('                  <div class="stanza">\n' + "\n".join(stanza) + '\n                  </div>')
            stanza.clear()
    for raw in text.split("\n"):
        if not raw.strip():
            flush()
            continue
        if raw.strip() == "—":
            flush()
            out.append('                  <hr class="poem__break">')
            continue
        n = len(raw) - len(raw.lstrip(" "))
        style = f' style="--i:{n}"' if n else ""
        stanza.append(f'                    <span class="ln"{style}>{inline(raw.strip())}</span>')
    flush()
    return "\n".join(out)


def poem_body(p):
    if p.get("columns"):
        cols = "\n".join(f'                <div class="poem__col">\n{lines(c)}\n                </div>' for c in p["columns"])
        return f'                <div class="poem__cols">\n{cols}\n                </div>'
    if p.get("text"):
        return lines(p["text"])
    frags = "\n".join(f'                  <p class="poem__fragment">“{esc(e)}”</p>' for e in p["excerpts"])
    return frags + '\n                  <p class="poem__pending">[Full text to come.]</p>'


def slide(i, p):
    return f'''            <article class="carousel__slide poem" id="{p['slug']}" aria-roledescription="slide" aria-label="{i + 1} of {len(POEMS)}">
              <div class="poem__bottle">
                <span class="fig-no" aria-hidden="true">{i + 1}</span>
                <img src="assets/ui/bottle-{GLASS[i % 3]}.svg" alt="" width="240" height="440">
              </div>
              <div class="poem__sheet">
                <span class="poem__meta">No. {i + 1:02d} — <time datetime="{p['iso']}">{p['date']}</time></span>
                <h2 class="poem__title">{esc(p['title'])}</h2>
                <div class="poem__text">
{poem_body(p)}
                </div>
              </div>
            </article>
'''


def contents():
    return "\n".join(
        f'            <li><a href="#{p["slug"]}" data-carousel-goto="{i}"><span>{ROMAN[i]}.</span> {esc(p["title"])}</a></li>'
        for i, p in enumerate(POEMS))


PAGE = f'''<!doctype html>
<!--
  MONSORIUM — Bottles at Sea, the reading room.
  Generated by tools/make-bottles-page.py from tools/poems.json; edit those, not this file.
  Shares styles.css (design + layout) and main.js (animations, carousel) with index.html.
-->
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bottles at Sea — Monsorium</title>
  <meta name="description" content="Bottles at Sea: poems by G.H. Mosseri, newest first.">
  <meta name="theme-color" content="#0B0236">
  <link rel="preload" href="assets/fonts/slowji.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="styles.css">
  <script>document.documentElement.classList.add('js');</script>
  <script src="main.js" defer></script>
</head>
<body class="page-bottles">
  <a class="skip-link" href="#main">Skip to content</a>

  <svg class="grain" aria-hidden="true" focusable="false">
    <filter id="grain-filter"><feTurbulence type="fractalNoise" baseFrequency="0.8" numOctaves="3" stitchTiles="stitch"/><feColorMatrix type="saturate" values="0"/></filter>
    <rect width="100%" height="100%" filter="url(#grain-filter)"/>
  </svg>

  <div class="masthead">
  <div class="ribbon" role="region" aria-label="Announcement">
    <div class="ribbon__track">
      <p class="ribbon__run"><span translate="no">MONSORIUM</span> <i aria-hidden="true">✶</i> [ribbon text to come] <i aria-hidden="true">✶</i> <span translate="no">MONSORIUM</span> <i aria-hidden="true">✶</i> [ribbon text to come] <i aria-hidden="true">✶</i></p>
      <p class="ribbon__run" aria-hidden="true"><span translate="no">MONSORIUM</span> <i>✶</i> [ribbon text to come] <i>✶</i> <span translate="no">MONSORIUM</span> <i>✶</i> [ribbon text to come] <i>✶</i></p>
    </div>
  </div>
  <header class="ovilats">
    <nav aria-label="Main">
      <ul class="nav-list">
        <li><a class="nav-btn nav-btn--home" href="index.html#home"><span>Home</span></a></li>
        <li><a class="nav-btn nav-btn--heretic" href="index.html#heretic"><span>The Heretic</span></a></li>
        <li><a class="nav-btn nav-btn--alleyway" href="index.html#alleyway"><span>The Alleyway</span></a></li>
        <li><a class="nav-btn nav-btn--bottles" href="index.html#bottles" aria-current="page"><span>Bottles at Sea</span></a></li>
        <li><a class="nav-btn nav-btn--conches" href="index.html#conches"><span>Conches</span></a></li>
      </ul>
    </nav>
  </header>
  </div>

  <main id="main">
    <section class="bottles reading" aria-labelledby="reading-title">
      <div class="corners" aria-hidden="true">
        <img class="corner corner--tl" src="assets/img/overlays/mary-hot_pink-overlay--bruise.webp" alt="">
        <img class="corner corner--tr" src="assets/img/overlays/tiger-orchid--bloom.webp" alt="">
        <img class="corner corner--bl" src="assets/img/overlays/magenta_dark-blue_assets-combined--bloom.webp" alt="">
        <img class="corner corner--br" src="assets/img/overlays/red-cyber-asset--bloom.webp" alt="">
      </div>
      <div class="decor bottles__dots" aria-hidden="true"></div>
      <img class="decor bottles__meadow" src="assets/img/spacers/palegreen-overlay--meadow.webp" alt="" aria-hidden="true">
      <svg class="decor bottles__waves" viewBox="0 0 1440 120" preserveAspectRatio="none" aria-hidden="true">
        <path d="M0 40 C120 70 240 10 360 40 C480 70 600 10 720 40 C840 70 960 10 1080 40 C1200 70 1320 10 1440 40" fill="none" stroke="#942C5B" stroke-width="5"/>
        <path d="M0 70 C120 100 240 40 360 70 C480 100 600 40 720 70 C840 100 960 40 1080 70 C1200 100 1320 40 1440 70" fill="none" stroke="#0B0236" stroke-width="3" stroke-dasharray="2 12" stroke-linecap="round"/>
      </svg>

      <div class="bottles__inner">
        <a class="reading__back" href="index.html#bottles">← Back to the shore</a>
        <span class="kicker">IV. — Creative Writing</span>
        <h1 id="reading-title" class="section-title">Bottles at Sea</h1>

        <div class="plate carousel" data-carousel data-carousel-hash aria-roledescription="carousel" aria-label="Poems">
          <p class="plate__head"><span>Taf. IV</span><span>Flaschenpost — the reading room</span><span data-carousel-count>1 / {len(POEMS)}</span></p>
          <div class="carousel__viewport" aria-live="polite">
{"".join(slide(i, p) for i, p in enumerate(POEMS))}          </div>
          <div class="carousel__controls">
            <button class="arrow-btn arrow-btn--prev" type="button" data-carousel-prev aria-label="Previous poem"></button>
            <span class="carousel__count" data-carousel-count>1 / {len(POEMS)}</span>
            <button class="arrow-btn" type="button" data-carousel-next aria-label="Next poem"></button>
          </div>
          <p class="plate__foot"><span translate="no">Monsorium Konv.-Lexikon, 1. Aufl.</span><span>Writing set adrift</span><span>Newest first</span></p>
        </div>

        <nav class="reading__contents" aria-label="All poems">
          <h2 class="reading__contents-title">Contents</h2>
          <ol>
{contents()}
          </ol>
        </nav>
      </div>
      <p class="colophon"><span>© MMXXVI <span translate="no">Monsorium</span> — all bodies reserved</span></p>
    </section>
  </main>
</body>
</html>
'''

if __name__ == "__main__":
    (ROOT / "bottles.html").write_text(PAGE)
    print(f"bottles.html — {len(POEMS)} poems")
