#!/usr/bin/env python3
"""Write art.html, the Alleyway viewing room, from tools/art.json.

    python3 tools/make-art-page.py

One clay frame holds the piece on view; the neighbours wait on either side,
angled in perspective and blurred by distance. The frame resizes to each
piece's orientation and the room advances by itself every 17 seconds.
Each piece is addressable as art.html#<slug>.
"""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ART = json.loads((ROOT / "tools" / "art.json").read_text())
INTERVAL = 17  # seconds between automatic changes


def esc(s):
    return html.escape(s)


def piece(i, a):
    title = esc(a["title"])
    return (f'          <figure class="art-piece" id="{a["slug"]}" data-w="{a["w"]}" data-h="{a["h"]}" '
            f'data-no="{a["no"]}" data-title="{title}" data-date="{esc(a["date"])}" data-iso="{a["iso"]}" '
            f'data-medium="{esc(a["medium"])}" data-section="{esc(a["section"])}" '
            f'aria-roledescription="slide" aria-label="{i + 1} of {len(ART)}">\n'
            f'            <img src="assets/img/art/{a["slug"]}.webp" alt="{esc(a["alt"])}" width="{a["w"]}" height="{a["h"]}"'
            f'{"" if i < 3 else " loading=\"lazy\""}>\n'
            f'          </figure>\n')


PAGE = f'''<!doctype html>
<!--
  MONSORIUM — the Alleyway viewing room.
  Generated by tools/make-art-page.py from tools/art.json; edit those, not this file.
  Shares styles.css and main.js with index.html.
-->
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>The Alleyway — Monsorium</title>
  <meta name="description" content="The Alleyway: graphic and digital art by G.H. Mosseri.">
  <meta name="theme-color" content="#0B0236">
  <link rel="stylesheet" href="styles.css">
  <script>document.documentElement.classList.add('js');</script>
  <script src="main.js" defer></script>
</head>
<body class="page-art">
  <a class="skip-link" href="#main">Skip to content</a>

  <svg class="grain" aria-hidden="true" focusable="false">
    <filter id="grain-filter"><feTurbulence type="fractalNoise" baseFrequency="0.8" numOctaves="3" stitchTiles="stitch"/><feColorMatrix type="saturate" values="0"/></filter>
    <rect width="100%" height="100%" filter="url(#grain-filter)"/>
  </svg>

  <div class="masthead">
  <div class="ribbon" role="region" aria-label="Announcement">
    <div class="ribbon__track">
      <p class="ribbon__run"><span translate="no">MONSORIUM</span> <i aria-hidden="true">✶</i> [ribbon text to come] <i aria-hidden="true">✶</i> <span translate="no">MONSORIUM</span> <i aria-hidden="true">✶</i> [ribbon text to come] <i aria-hidden="true">✶</i></p>
      <p class="ribbon__run" aria-hidden="true"><span translate="no">MONSORIUM</span> <i>✶</i> [ribbon text to come] <i>✶</i> <span translate="no">MONSORIUM</span> <i>✶</i> [ribbon text to come] <i>✶</i></p>
    </div>
  </div>
  <header class="ovilats">
    <nav aria-label="Main">
      <ul class="nav-list">
        <li><a class="nav-btn nav-btn--home" href="index.html#home"><span>Home</span></a></li>
        <li><a class="nav-btn nav-btn--heretic" href="index.html#heretic"><span>The Heretic</span></a></li>
        <li><a class="nav-btn nav-btn--alleyway" href="index.html#alleyway" aria-current="page"><span>The Alleyway</span></a></li>
        <li><a class="nav-btn nav-btn--bottles" href="index.html#bottles"><span>Bottles at Sea</span></a></li>
        <li><a class="nav-btn nav-btn--conches" href="index.html#conches"><span>Conches</span></a></li>
      </ul>
    </nav>
  </header>
  </div>

  <main id="main">
    <section class="alleyway viewing" aria-labelledby="viewing-title">
      <div class="corners" aria-hidden="true">
        <img class="corner corner--tl" src="assets/img/overlays/red-cyber-asset--venom.webp" alt="">
        <img class="corner corner--tr" src="assets/img/overlays/magenta_dark-blue_assets-combined--venom.webp" alt="">
        <img class="corner corner--bl" src="assets/img/overlays/blank-nouveau-frame--venom.webp" alt="">
        <img class="corner corner--br" src="assets/img/overlays/magenta-cyber-asset--venom.webp" alt="">
      </div>
      <div class="decor alleyway__scan" aria-hidden="true"></div>

      <div class="viewing__head">
        <a class="reading__back" href="index.html#alleyway">← Back to the Alleyway</a>
        <span class="kicker">III. — The Portfolio</span>
        <h1 id="viewing-title" class="section-title">The Alleyway</h1>
      </div>

      <div class="viewer" data-artviewer data-interval="{INTERVAL}" aria-roledescription="carousel" aria-label="Artworks">
        <div class="viewer__stage">
          <div class="viewer__ghosts" aria-hidden="true"></div>
          <button class="arrow-btn arrow-btn--prev viewer__arrow" type="button" data-art-prev aria-label="Previous piece"></button>
          <div class="frame frame--gilt art-frame">
            <div class="frame__inner art-frame__window">
{"".join(piece(i, a) for i, a in enumerate(ART))}            </div>
          </div>
          <button class="arrow-btn viewer__arrow" type="button" data-art-next aria-label="Next piece"></button>
        </div>

        <div class="art-caption" aria-live="polite">
          <span class="art-caption__no" data-art-no>{ART[0]["no"]}.</span>
          <cite class="art-caption__title" data-art-title>{esc(ART[0]["title"])}</cite>
          <span class="art-caption__meta"><time data-art-date datetime="{ART[0]["iso"]}">{esc(ART[0]["date"])}</time> · <span data-art-medium>{esc(ART[0]["medium"])}</span></span>
        </div>
        <button class="viewer__pause" type="button" data-art-pause aria-pressed="false">Pause slideshow</button>
      </div>
      <p class="colophon"><span>© MMXXVI <span translate="no">Monsorium</span> — all bodies reserved</span></p>
    </section>
  </main>
</body>
</html>
'''

if __name__ == "__main__":
    (ROOT / "art.html").write_text(PAGE)
    print(f"art.html — {len(ART)} pieces")
